apiVersion: apps/v1
kind: Deployment
metadata:
  name: dune-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dune-backend
  template:
    metadata:
      labels:
        app: dune-backend
    spec:
      volumes:
        - name: static-files
          emptyDir: {}
      containers:
      - name: dune-backend
        image: dazdd/dune-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: static-files
            mountPath: /app/staticfiles
        env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_PORT
          - name: PYTHONPATH
            value: "/usr/src/app:/usr/src/app/gameapp"
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secret

apiVersion: v1
kind: Service
metadata:
  name: dune-backend-service
spec:
  selector:
    app: dune-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP


