apiVersion: apps/v1
kind: Deployment
metadata:
  name: dune-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dune-backend
  template:
    metadata:
      labels:
        app: dune-backend
    spec:
      containers:
      - name: dune-backend
        image: dazdd/dune-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: "dune_card_game"
        - name: DB_USER
          value: "taylor"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: PYTHONPATH
          value: "/usr/src/app:/usr/src/app/gameapp"
---
apiVersion: v1
kind: Service
metadata:
  name: dune-backend-service
spec:
  selector:
    app: dune-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP


