apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: ingress-nginx
data:
  default.conf: |
    server {
        listen 80;
        server_name 45.79.231.182;

        location / {
            proxy_pass http://dune-backend-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /media {
            alias /app/gameapp/media;
            autoindex on;
            try_files $uri $uri/ =404;
            types {
                image/jpeg jpeg jpg;
                image/png png;
                image/gif gif;
                image/webp webp;
            }
        }

        location /static {
            alias /app/staticfiles/static;
        }
    }


