apiVersion: apps/v1
kind: Deployment
metadata:
  name: dune-frontend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dune-frontend
  template:
    metadata:
      labels:
        app: dune-frontend
    spec:
      volumes:
      - name: nginx-config
        emptyDir: {}
      - name: nginx-config-template
        configMap:
          name: frontend-nginx-config
      initContainers:
      - name: init-nginx-config
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache gettext
            envsubst < /etc/nginx/template/default.conf > /etc/nginx/conf.d/default.conf
        env:
        - name: REACT_APP_API_URL
          value: "http://dune-backend-service:8000"
        - name: REACT_APP_MEDIA_URL
          value: "http://dune-backend-service:8000"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-config-template
          mountPath: /etc/nginx/template
      containers:
      - name: dune-frontend
        image: dazdd/dune-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: dune-frontend-service
spec:
  selector:
    app: dune-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
