apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - name: controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:v1.3.0
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/frontend-nginx-config  # Changed this line
        volumeMounts:
        - name: custom-config
          mountPath: /etc/nginx/custom-config
          readOnly: true
      volumes:
      - name: custom-config
        configMap:
          name: frontend-nginx-config
          items:
          - key: default.conf  # Changed this line
            path: custom-config.conf


