services:
  - type: web
    name: dune-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Dunecardgame.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dune-card-game-db
          property: connectionString
      - key: DB_NAME
        fromDatabase:
          name: dune-card-game-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: dune-card-game-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dune-card-game-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: dune-card-game-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dune-card-game-db
          property: port

databases:
  - name: dune-card-game-db
    databaseName: dune_card_game
    user: taylor