# Generated by Django 5.0.4 on 2025-01-11 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('errata', models.TextField(blank=True, db_column='Errata, Clarification, and Misprint Notes', null=True)),
                ('set', models.CharField(db_column='Set', max_length=255)),
                ('rarity', models.CharField(db_column='Rarity', max_length=255)),
                ('deck', models.CharField(db_column='Deck', max_length=255)),
                ('cost', models.CharField(db_column='Cost', max_length=255)),
                ('allegiance', models.CharField(db_column='Allegiance', max_length=255)),
                ('talent_req', models.CharField(db_column='Talent Req', max_length=255)),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('subtype1', models.CharField(blank=True, db_column='Subtype 1', max_length=255, null=True)),
                ('subtype2', models.CharField(blank=True, db_column='Subtype 2', max_length=255, null=True)),
                ('subtype3', models.CharField(blank=True, db_column='Subtype 3', max_length=255, null=True)),
                ('subtype4', models.CharField(blank=True, db_column='Subtype 4', max_length=255, null=True)),
                ('talent1', models.CharField(blank=True, db_column='Talent 1', max_length=255, null=True)),
                ('talent2', models.CharField(blank=True, db_column='Talent 2', max_length=255, null=True)),
                ('talent3', models.CharField(blank=True, db_column='Talent 3', max_length=255, null=True)),
                ('command', models.CharField(db_column='Command', max_length=255)),
                ('resistance', models.CharField(db_column='Resistance', max_length=255)),
                ('operation_text', models.TextField(blank=True, db_column='Operation Text', null=True)),
                ('flavor_text', models.TextField(blank=True, db_column='Flavor Text', null=True)),
                ('artist', models.CharField(db_column='Artist', max_length=255)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='dune_card_images/')),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('model_binary', models.BinaryField()),
            ],
            options={
                'db_table': 'dune-cards',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('keyboard_pattern', models.TextField(null=True)),
                ('suspicious_score', models.FloatField(default=0.0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
