# Generated by Django 5.0.4 on 2024-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('errata', models.TextField(blank=True, db_column='Errata, Clarification, and Misprint Notes', null=True)),
                ('set', models.CharField(db_column='Set', max_length=255)),
                ('rarity', models.CharField(db_column='Rarity', max_length=255)),
                ('deck', models.CharField(db_column='Deck', max_length=255)),
                ('cost', models.CharField(db_column='Cost', max_length=255)),
                ('allegiance', models.CharField(db_column='Allegiance', max_length=255)),
                ('talent_req', models.CharField(db_column='Talent Req', max_length=255)),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('subtype1', models.CharField(blank=True, db_column='Subtype 1', max_length=255, null=True)),
                ('subtype2', models.CharField(blank=True, db_column='Subtype 2', max_length=255, null=True)),
                ('subtype3', models.CharField(blank=True, db_column='Subtype 3', max_length=255, null=True)),
                ('subtype4', models.CharField(blank=True, db_column='Subtype 4', max_length=255, null=True)),
                ('talent1', models.CharField(blank=True, db_column='Talent 1', max_length=255, null=True)),
                ('talent2', models.CharField(blank=True, db_column='Talent 2', max_length=255, null=True)),
                ('talent3', models.CharField(blank=True, db_column='Talent 3', max_length=255, null=True)),
                ('command', models.CharField(db_column='Command', max_length=255)),
                ('resistance', models.CharField(db_column='Resistance', max_length=255)),
                ('operation_text', models.TextField(blank=True, db_column='Operation Text', null=True)),
                ('flavor_text', models.TextField(blank=True, db_column='Flavor Text', null=True)),
                ('artist', models.CharField(db_column='Artist', max_length=255)),
                ('image_file', models.CharField(blank=True, db_column='image_file', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cards2',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
