# Generated by Django 5.0.4 on 2024-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(default=[], max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='dune_card_images/'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
