name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PostgreSQL environment variables
      run: |
        echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Debug ECR URL
      run: |
        echo "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dune-cf-backend:latest"

    - name: Build and push backend Docker image
      working-directory: ./Dunecardgame
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        docker build -t dune-cf-backend:latest -f Dockerfile .
        docker tag dune-cf-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dune-cf-backend:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dune-cf-backend:latest

    - name: Build frontend Docker image
      working-directory: Dunecardgame/Dune-Front-End
      run: docker build -t dune-cf-frontend:latest .

    - name: Extract frontend build artifacts
      run: |
        container_id=$(docker create dune-cf-frontend:latest)
        docker cp $container_id:/usr/share/nginx/html ./dist
        docker rm $container_id

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install AWS CLI and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli==1.27.160 botocore==1.29.160 s3transfer==0.6.1

    - name: Sync files to S3
      run: aws s3 sync ./dist s3://dune-bucket-23 --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

    - name: Get VPC and Subnet Info
      run: |
        VPC_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].VpcId' --output text)
        CURRENT_SUBNET_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].SubnetId' --output text)
        AZ=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)
        echo "VPC ID: $VPC_ID"
        echo "Current Subnet ID: $CURRENT_SUBNET_ID"
        echo "Availability Zone: $AZ"
        echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
        echo "CURRENT_SUBNET_ID=$CURRENT_SUBNET_ID" >> $GITHUB_ENV
        echo "AZ=$AZ" >> $GITHUB_ENV

    - name: Check for Existing Public Subnet
      run: |
        PUBLIC_SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=${{ env.VPC_ID }}" "Name=map-public-ip-on-launch,Values=true" --query 'Subnets[0].SubnetId' --output text)
        if [ "$PUBLIC_SUBNET_ID" != "None" ]; then
          echo "Existing public subnet found: $PUBLIC_SUBNET_ID"
          echo "PUBLIC_SUBNET_ID=$PUBLIC_SUBNET_ID" >> $GITHUB_ENV
        else
          echo "No existing public subnet found. Creating new one."
        fi

    - name: Create Public Subnet (if needed)
      if: env.PUBLIC_SUBNET_ID == ''
      run: |
        IGW_ID=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=${{ env.VPC_ID }}" --query 'InternetGateways[0].InternetGatewayId' --output text)
        NEW_SUBNET_ID=$(aws ec2 create-subnet --vpc-id ${{ env.VPC_ID }} --cidr-block 10.0.2.0/24 --availability-zone ${{ env.AZ }} --query 'Subnet.SubnetId' --output text)
        echo "New Subnet ID: $NEW_SUBNET_ID"
        
        RT_ID=$(aws ec2 create-route-table --vpc-id ${{ env.VPC_ID }} --query 'RouteTable.RouteTableId' --output text)
        echo "New Route Table ID: $RT_ID"
        
        aws ec2 create-route --route-table-id $RT_ID --destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID
        aws ec2 associate-route-table --subnet-id $NEW_SUBNET_ID --route-table-id $RT_ID
        aws ec2 modify-subnet-attribute --subnet-id $NEW_SUBNET_ID --map-public-ip-on-launch
        
        echo "PUBLIC_SUBNET_ID=$NEW_SUBNET_ID" >> $GITHUB_ENV

    - name: Move EC2 to Public Subnet (if needed)
      if: env.CURRENT_SUBNET_ID != env.PUBLIC_SUBNET_ID
      run: |
          # Get instance details
          INSTANCE_AZ=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)
          echo "Instance Availability Zone: $INSTANCE_AZ"
      
          # Find a public subnet in the same AZ as the instance
          PUBLIC_SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=${{ env.VPC_ID }}" "Name=availabilityZone,Values=$INSTANCE_AZ" "Name=map-public-ip-on-launch,Values=true" --query 'Subnets[0].SubnetId' --output text)
          echo "Public Subnet ID in same AZ: $PUBLIC_SUBNET_ID"
      
          if [ "$PUBLIC_SUBNET_ID" == "None" ]; then
            echo "Error: No public subnet found in the same AZ as the instance"
            exit 1
          fi
      
          # Stop the instance if it's running
          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].State.Name' --output text)
          if [ "$INSTANCE_STATE" != "stopped" ]; then
            aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
            echo "Waiting for instance to stop..."
            aws ec2 wait instance-stopped --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          fi
      
          # Get existing network interfaces
          NETWORK_INTERFACES=$(aws ec2 describe-network-interfaces --filters "Name=attachment.instance-id,Values=${{ secrets.EC2_INSTANCE_ID }}" --query 'NetworkInterfaces[*].{Id:NetworkInterfaceId,SubnetId:SubnetId,DeviceIndex:Attachment.DeviceIndex}')
          echo "Existing Network Interfaces: $NETWORK_INTERFACES"
      
          # Check if there's already an interface in the public subnet
          PUBLIC_ENI_ID=$(echo "$NETWORK_INTERFACES" | jq -r '.[] | select(.SubnetId == "'$PUBLIC_SUBNET_ID'") | .Id')
      
          if [ -n "$PUBLIC_ENI_ID" ]; then
            echo "Network interface in public subnet already exists: $PUBLIC_ENI_ID"
          else
            # Create a new network interface in the public subnet
            NEW_ENI_ID=$(aws ec2 create-network-interface --subnet-id $PUBLIC_SUBNET_ID --description "New public interface" --query 'NetworkInterface.NetworkInterfaceId' --output text)
            echo "New Network Interface ID: $NEW_ENI_ID"
      
            # Get the security group ID
            SG_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].SecurityGroups[0].GroupId' --output text)
      
            # Attach the security group to the new network interface
            aws ec2 modify-network-interface-attribute --network-interface-id $NEW_ENI_ID --groups $SG_ID
      
            # Find the first available device index
            AVAILABLE_INDEX=$(echo "$NETWORK_INTERFACES" | jq -r '[.[].DeviceIndex] | max + 1')
      
            # Attach the new network interface to the instance
            ATTACHMENT_ID=$(aws ec2 attach-network-interface --network-interface-id $NEW_ENI_ID --instance-id ${{ secrets.EC2_INSTANCE_ID }} --device-index $AVAILABLE_INDEX --query 'AttachmentId' --output text)
            echo "Attachment ID: $ATTACHMENT_ID"
      
            # Modify instance attribute to use the new network interface as primary
            aws ec2 modify-instance-attribute --instance-id ${{ secrets.EC2_INSTANCE_ID }} --attachment "{\"AttachmentId\":\"$ATTACHMENT_ID\",\"DeleteOnTermination\":true}"
      
            PUBLIC_ENI_ID=$NEW_ENI_ID
          fi
      
          # Start the instance
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          echo "Waiting for instance to start..."
          aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
      
          # Ensure the public ENI is the primary network interface
          aws ec2 modify-network-interface-attribute --network-interface-id $PUBLIC_ENI_ID --attachment AttachmentId=$(aws ec2 describe-network-interfaces --network-interface-ids $PUBLIC_ENI_ID --query 'NetworkInterfaces[0].Attachment.AttachmentId' --output text),DeleteOnTermination=true
          aws ec2 modify-instance-attribute --instance-id ${{ secrets.EC2_INSTANCE_ID }} --network-interface "{\"DeviceIndex\": 0, \"NetworkInterfaceId\": \"$PUBLIC_ENI_ID\"}"
      
          # Remove other network interfaces
          for ENI in $(echo "$NETWORK_INTERFACES" | jq -r '.[].Id'); do
            if [ "$ENI" != "$PUBLIC_ENI_ID" ]; then
              aws ec2 detach-network-interface --attachment-id $(aws ec2 describe-network-interfaces --network-interface-ids $ENI --query 'NetworkInterfaces[0].Attachment.AttachmentId' --output text)
              aws ec2 delete-network-interface --network-interface-id $ENI
            fi
          done
      
    - name: Update Public IP
      run: |
          NEW_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "New Public IP: $NEW_PUBLIC_IP"
          echo "EC2_PUBLIC_IP=$NEW_PUBLIC_IP" >> $GITHUB_ENV
      
    - name: Verify Instance Subnet
      run: |
          INSTANCE_SUBNET_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].SubnetId' --output text)
          echo "Instance Subnet ID: $INSTANCE_SUBNET_ID"
          echo "Public Subnet ID: ${{ env.PUBLIC_SUBNET_ID }}"
          if [ "$INSTANCE_SUBNET_ID" != "${{ env.PUBLIC_SUBNET_ID }}" ]; then
            echo "Error: Instance is not in the public subnet"
            exit 1
          fi

    - name: Check VPC and Internet Gateway
      run: |
        echo "VPC ID: ${{ env.VPC_ID }}"
        aws ec2 describe-vpcs --vpc-ids ${{ env.VPC_ID }} --query 'Vpcs[0].{CidrBlock:CidrBlock,State:State}'
        echo "Checking Internet Gateway..."
        aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=${{ env.VPC_ID }}" --query 'InternetGateways[*].{InternetGatewayId:InternetGatewayId,State:Attachments[0].State}'

    - name: Check Security Group Inbound Rules
      run: |
          SG_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].SecurityGroups[0].GroupId' --output text)
          aws ec2 describe-security-group-rules --filters Name="group-id",Values="$SG_ID" --query 'SecurityGroupRules[?!IsEgress]'
    
    - name: Ping Instance
      run: |
            ping -c 4 ${{ env.EC2_PUBLIC_IP }} || echo "Ping failed"

    - name: Check SSM Session Manager
      run: |
            aws ssm start-session --target ${{ secrets.EC2_INSTANCE_ID }} --document-name AWS-StartInteractiveCommand --parameters command="echo SSM connection successful" || echo "SSM connection failed"

    - name: Check Route Table
      run: |
        echo "Subnet ID: ${{ env.PUBLIC_SUBNET_ID }}"
        aws ec2 describe-route-tables --filters "Name=association.subnet-id,Values=${{ env.PUBLIC_SUBNET_ID }}" --query 'RouteTables[*].Routes'

    - name: Check Network Interface
      run: |
        aws ec2 describe-network-interfaces --filters "Name=attachment.instance-id,Values=${{ secrets.EC2_INSTANCE_ID }}" --query 'NetworkInterfaces[*].{SubnetId:SubnetId,PrivateIpAddress:PrivateIpAddress,PublicIp:Association.PublicIp,Status:Status}'

    - name: Check Security Group Rules
      run: |
        SG_ID=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].SecurityGroups[0].GroupId' --output text)
        echo "Security Group ID: $SG_ID"
        aws ec2 describe-security-group-rules --filters Name="group-id",Values="$SG_ID" --query 'SecurityGroupRules[?IpProtocol==`tcp` && FromPort==`22`]'

    - name: Check Network ACL Rules
      run: |
        NACL_ID=$(aws ec2 describe-network-acls --filters Name=association.subnet-id,Values=${{ env.PUBLIC_SUBNET_ID }} --query 'NetworkAcls[0].NetworkAclId' --output text)
        echo "Network ACL ID: $NACL_ID"
        aws ec2 describe-network-acls --network-acl-ids $NACL_ID

    - name: Test SSH Connection
      continue-on-error: true  # This allows the workflow to continue even if this step fails
      run: |
          ssh-keygen -t rsa -b 4096 -f ./id_rsa -N ""
          aws ec2-instance-connect send-ssh-public-key --instance-id ${{ secrets.EC2_INSTANCE_ID }} --availability-zone ${{ env.AZ }} --instance-os-user ec2-user --ssh-public-key file://./id_rsa.pub
          ssh -o StrictHostKeyChecking=no -i ./id_rsa ec2-user@${{ env.EC2_PUBLIC_IP }} "echo Connection successful"

    - name: Deploy to EC2
      env:
        EC2_USER: ec2-user
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${{ env.EC2_PUBLIC_IP }} '
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dune-cf-backend:latest &&
          docker stop dune-backend || true &&
          docker rm dune-backend || true &&
          docker run -d --name dune-backend -p 8000:8000 \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dune-cf-backend:latest
        '
        rm private_key.pem

    - name: Deploy using Systems Manager (Fallback)
      if: failure()
      run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dune-cf-backend:latest",
              "docker stop dune-backend || true",
              "docker rm dune-backend || true",
              "docker run -d --name dune-backend -p 8000:8000 -e DB_NAME=${{ secrets.DB_NAME }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dune-cf-backend:latest"
            ]' \
            --output text