name: CI/CD Pipeline for LKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Dunecardgame/Dune-Front-End
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Dunecardgame
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dune-backend:latest

    - name: Install Linode CLI
      run: |
        pip install linode-cli

    - name: Configure Linode CLI
      env:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      run: |
        echo "LINODE_CLI_TOKEN=$LINODE_CLI_TOKEN" >> $GITHUB_ENV

    - name: Get LKE kubeconfig
      run: |
        linode-cli lke kubeconfig-view ${{ secrets.LKE_CLUSTER_ID }} --text > kubeconfig.yaml
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to LKE
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f ./Dunecardgame/k8s/

    - name: Verify deployment
      run: |
        kubectl --kubeconfig=kubeconfig.yaml get pods
        kubectl --kubeconfig=kubeconfig.yaml get services

#push






