name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: > 
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Backend build and push to ECR
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend Docker image
      run: |
        docker build -t DUNE-backend:latest -f backend/Dockerfile .
        docker tag DUNE-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/DUNE-backend:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/DUNE-backend:latest

    # Frontend build and deploy to S3
    - name: Build frontend Docker image
      run: docker build -t DUNE-frontend:latest -f frontend/Dockerfile .

    - name: Extract frontend build artifacts
      run: |
        container_id=$(docker create DUNE-frontend:latest)
        docker cp $container_id:/app/build ./build
        docker rm $container_id

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your region

    - name: Sync files to S3
      run: aws s3 sync ./build s3://dune-bucket-23 --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --E3P5XUMZQ1QJMV E3P5XUMZQ1QJMV --paths "/*"

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p docker dune-app --region ${{ secrets.AWS_REGION }}
        eb deploy
