name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push frontend Docker image
      run: |
        cd Dunecardgame/Dune-Front-End
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest

    - name: Build and push backend Docker image
      run: |
          cd Dunecardgame
          echo "Building Docker image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-backend:${{ github.sha }} .
          echo "Pushing Docker image in chunks..."
          docker save ${{ secrets.DOCKER_USERNAME }}/dune-backend:${{ github.sha }} | gzip | split -b 20m - docker-image-chunk
          for chunk in docker-image-chunk*; do
            echo "Pushing chunk $chunk"
            curl -X POST -H "Content-Type: application/octet-stream" --data-binary @$chunk \
              -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
              "https://registry-1.docker.io/v2/${{ secrets.DOCKER_USERNAME }}/dune-backend/blobs/uploads/?digest=sha256:$(sha256sum $chunk | cut -d' ' -f1)"
          done
          echo "Push completed. Listing images:"
          docker images | grep dune-backend

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'
  
    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig
          kubectl --kubeconfig=kubeconfig get nodes
          kubectl --kubeconfig=kubeconfig apply -f Dunecardgame/k8s/

#push






