name: CI/CD Pipeline for LKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest ./Dunecardgame/Dune-Front-End

    - name: Push Frontend Docker image in chunks
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest | gzip | split -b 20m - frontend-image-chunk
        for chunk in frontend-image-chunk*; do
          curl -X POST -H "Content-Type: application/octet-stream" --data-binary @$chunk \
            -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://registry-1.docker.io/v2/${{ secrets.DOCKER_USERNAME }}/dune-frontend/blobs/uploads/?digest=sha256:$(sha256sum $chunk | cut -d' ' -f1)"
        done

    - name: Build Backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-backend:latest ./Dunecardgame

    - name: Push Backend Docker image in chunks
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/dune-backend:latest | gzip | split -b 20m - backend-image-chunk
        for chunk in backend-image-chunk*; do
          curl -X POST -H "Content-Type: application/octet-stream" --data-binary @$chunk \
            -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://registry-1.docker.io/v2/${{ secrets.DOCKER_USERNAME }}/dune-backend/blobs/uploads/?digest=sha256:$(sha256sum $chunk | cut -d' ' -f1)"
        done

    - name: Install Linode CLI
      run: |
        pip install linode-cli
  
    - name: Configure Linode CLI
      env:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      run: |
        echo "LINODE_CLI_TOKEN=$LINODE_CLI_TOKEN" >> $GITHUB_ENV
        echo "Linode CLI Token is set: ${{ secrets.LINODE_CLI_TOKEN != '' }}"
    
    - name: Test Linode CLI
      run: |
        linode-cli --version
        linode-cli regions list

    - name: Set Cluster ID
      run: |
        echo "CLUSTER_ID=204261" >> $GITHUB_ENV

    - name: Get LKE kubeconfig
      run: |
        echo "Using Cluster ID: $CLUSTER_ID"
        linode-cli lke kubeconfig-view $CLUSTER_ID --text > kubeconfig.yaml
        if [ $? -ne 0 ]; then
          echo "Error: Failed to get kubeconfig"
          exit 1
        fi
        echo "Successfully retrieved kubeconfig"
        # Redact sensitive information before displaying
        sed -i 's/certificate-authority-data:.*/certificate-authority-data: REDACTED/' kubeconfig.yaml
        sed -i 's/token:.*/token: REDACTED/' kubeconfig.yaml
        cat kubeconfig.yaml

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to LKE
      run: |
        # Use the kubeconfig we just retrieved
        export KUBECONFIG=./kubeconfig.yaml
        
        # Apply your Kubernetes configurations
        kubectl apply -f ./Dunecardgame/k8s/

    - name: Verify deployment
      run: |
        export KUBECONFIG=./kubeconfig.yaml
        kubectl get pods
        kubectl get services

#push






