name: CI/CD Pipeline for LKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Debug Docker info
      run: |
        echo "Logged in as: $(docker info | grep Username)"
        docker version

    - name: Build Frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest -f ./Dunecardgame/Dune-Front-End/Dockerfile ./Dunecardgame/Dune-Front-End

    - name: Push Frontend Docker image in chunks
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/dune-frontend:latest | gzip | split -b 20m - frontend-image-chunk
        for chunk in frontend-image-chunk*; do
          curl -X POST -H "Content-Type: application/octet-stream" --data-binary @$chunk \
            -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://registry-1.docker.io/v2/${{ secrets.DOCKER_USERNAME }}/dune-frontend/blobs/uploads/?digest=sha256:$(sha256sum $chunk | cut -d' ' -f1)"
        done

    - name: Build Backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dune-backend:latest -f ./Dunecardgame/Dockerfile ./Dunecardgame

    - name: Push Backend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dune-backend:latest

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Linode CLI
      run: |
        pip install linode-cli
  
    - name: Configure Linode CLI
      env:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      run: |
        mkdir -p ~/.config/linode-cli
        echo -e "[DEFAULT]\ntoken = $LINODE_CLI_TOKEN\nregion = us-west" > ~/.config/linode-cli/config

    - name: Test Linode CLI
      env:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      run: |
        linode-cli --version
        linode-cli regions list

    - name: Set Cluster ID
      run: |
        echo "CLUSTER_ID=204261" >> $GITHUB_ENV

    - name: Get and process LKE kubeconfig
      env:
        LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      run: |
        echo "Using Cluster ID: $CLUSTER_ID"
        linode-cli lke kubeconfig-view $CLUSTER_ID --text > kubeconfig.tmp
        if [ $? -ne 0 ]; then
          echo "Error: Failed to get kubeconfig"
          exit 1
        fi
        echo "Successfully retrieved kubeconfig"
        
        echo "Content of retrieved kubeconfig:"
        cat kubeconfig.tmp
        
        # Extract the base64 content, ignoring the first line
        BASE64_CONTENT=$(tail -n +2 kubeconfig.tmp | tr -d '\n')
        echo "Extracted base64 content:"
        echo "$BASE64_CONTENT"
        
        # Decode the base64 content
        echo "$BASE64_CONTENT" | base64 -d > ${GITHUB_WORKSPACE}/kubeconfig.yaml
        
        echo "Decoded kubeconfig content:"
        cat ${GITHUB_WORKSPACE}/kubeconfig.yaml
      
    - name: Validate YAML
      run: |
        python -c "import yaml; print(yaml.safe_load(open('${GITHUB_WORKSPACE}/kubeconfig.yaml')))"

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to LKE
      run: |
        export KUBECONFIG=${GITHUB_WORKSPACE}/kubeconfig.yaml
        
        kubectl config view
        
        kubectl apply -f ./Dunecardgame/k8s/
      
    - name: Verify deployment
      run: |
        export KUBECONFIG=${GITHUB_WORKSPACE}/kubeconfig.yaml
        kubectl get pods
        kubectl get services











#push






